Version 1.3.0
hivemq/hivemq-testcontainer pull request #62
Opened 2020-09-22 13:27 UTC by YannickWeber

**Changes**

* added the ability to load gradle based HiveMQ extensions
* Array classes are no longer put into shrinkwrap archives
* switched to jetbrains annotations

2020-09-22 13:34 UTC, SgtSilvio commented on build.gradle
> +        sourceCompatibility = JavaVersion.VERSION_11
this is a major change, projects using Java 8 can no longer use the testcontainer as dependency

2020-09-22 13:34 UTC, SgtSilvio commented on build.gradle
> +        jetbrainsAnnotationsVersion = '20.1.0'
why twice?

2020-09-22 13:35 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +    private static final @NotNull String GRADLE_WRAPPER_COMMAND = "./gradlew";
this will not work on Windows

2020-09-23 11:02 UTC, YannickWeber commented
Tested on Windows 10

2020-09-23 11:22 UTC, SgtSilvio commented on readme.md
> +testCompile "junit:junit:4.13"
```suggestion
testImplementation "com.hivemq:hivemq-testcontainer-junit4:1.3.0"
testImplementation "junit:junit:4.13"
```

2020-09-23 11:22 UTC, SgtSilvio commented on readme.md
> +testCompile "org.junit.jupiter:junit-jupiter-api:5.6.1"
```suggestion
testImplementation "com.hivemq:hivemq-testcontainer-junit5:1.3.0"
testImplementation "org.junit.jupiter:junit-jupiter-api:5.6.1"
testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.6.1"
```

2020-12-16 09:12 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +import org.testcontainers.shaded.org.apache.commons.lang.SystemUtils;
use right imports

2020-12-16 09:13 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/HiveMQTestContainerCore.java
>  import org.testcontainers.shaded.com.google.common.io.Files;
Use right import

2020-12-16 09:18 UTC, SgtSilvio commented on readme.md
> +                "project name", "project version").get());
please update to new API

2020-12-16 09:18 UTC, SgtSilvio commented on readme.md
> +                "project name", "project version").get());
please update to new API

2020-12-16 09:21 UTC, SgtSilvio commented on junit5/src/test/resources/gradle-extension/settings.gradle
> +        id 'com.hivemq.extension' version '0.1.2'
```suggestion
        id 'com.hivemq.extension' version '1.0.0'
```

2020-12-16 09:25 UTC, SgtSilvio commented on junit5/src/test/resources/gradle-extension/build.gradle
> +}
can be removed

2020-12-16 09:26 UTC, SgtSilvio commented on junit4/src/test/resources/gradle-extension/settings.gradle
> +        id 'com.hivemq.extension' version '0.1.2'
```suggestion
        id 'com.hivemq.extension' version '1.0.0'
```

2020-12-16 09:27 UTC, SgtSilvio commented on junit4/src/test/resources/gradle-extension/build.gradle
> +}
can be removed

2020-12-16 09:29 UTC, SgtSilvio commented on junit5/src/test/java/com/hivemq/testcontainer/junit5/ContainerWithoutPlatformExtensions.java
> +public class ContainerWithoutPlatformExtensions {
missing "IT" => ContainerWithoutPlatformExtensionsIT

2020-12-16 09:29 UTC, SgtSilvio commented on junit5/src/test/java/com/hivemq/testcontainer/junit5/ContainerWithGradleExtension.java
> +public class ContainerWithGradleExtension {
missing "IT" => ContainerWithGradleExtensionIT

2020-12-16 09:30 UTC, SgtSilvio commented on junit4/src/test/java/com/hivemq/testcontainer/junit4/ContainerWithoutPlatformExtensions.java
> +public class ContainerWithoutPlatformExtensions {
missing "IT" => ContainerWithoutPlatformExtensionsIT

2020-12-16 09:30 UTC, SgtSilvio commented on junit4/src/test/java/com/hivemq/testcontainer/junit4/ContainerWithGradleExtension.java
> +public class ContainerWithGradleExtension {
missing "IT" => ContainerWithGradleExtensionIT

2020-12-16 09:41 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +        return new GradleHiveMQExtensionSupplier("build.gradle");
Imho it makes more sense that to pass the root directory of the project as argument because this would be agnostic to the groovy and kotlin dsl

2020-12-16 09:42 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +                return GRADLE_WRAPPER_BASH_COMMAND;
```suggestion
                return gradleWrapperBashFile.getAbsolutePath();
```
to be consistent

2020-12-16 09:43 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +    private static final @NotNull String GRADLE_WRAPPER_BASH_COMMAND = "./gradlew";
not needed if you apply the below suggestion

2020-12-16 09:50 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final ProcessBuilder processBuilder = new ProcessBuilder();
processBuilder -> extensionProcessBuilder

2020-12-16 09:51 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final Process gradleBuild = processBuilder.start();
gradleBuild -> extensionProcess

2020-12-16 09:52 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final int extensionBuildExitCode = gradleBuild.waitFor();
extensionBuildExitCode -> extensionZipExitCode

2020-12-16 09:52 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final ProcessBuilder propertiesTask = new ProcessBuilder();
propertiesTask -> propertiesProcessBuilder

2020-12-16 09:52 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final Process propertiesTaskProcess = propertiesTask.start();
propertiesTaskProcess -> propertiesProcess

2020-12-16 09:58 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/HiveMQTestContainerCore.java
> +    }
unnecessary

2020-12-16 09:58 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final @NotNull String gradleBuild) {
maybe pass a File instead of a String

2020-12-16 10:00 UTC, SgtSilvio commented on junit4/src/test/java/com/hivemq/testcontainer/junit4/ContainerWithoutPlatformExtensions.java
> +    public void removeKafkaExtensions() throws InterruptedException {
```suggestion
    public void removeKafkaExtension() throws InterruptedException {
```

2020-12-16 10:03 UTC, SgtSilvio commented on junit5/src/test/java/com/hivemq/testcontainer/junit5/ContainerWithoutPlatformExtensions.java
> +    public void removeKafkaExtensions() throws InterruptedException {
removeKafkaExtensions -> removeKafkaExtension

2020-12-16 10:04 UTC, SgtSilvio requested changes
see comments

2020-12-16 10:38 UTC, YannickWeber commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +                return GRADLE_WRAPPER_BASH_COMMAND;
This does not work.

2020-12-16 15:20 UTC, SgtSilvio commented on core/build.gradle
> +    compile group: 'org.apache.commons', name: 'commons-lang3', version: commonsLangVersion
```suggestion
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: commonsLangVersion
```

2020-12-16 15:23 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +        return new GradleHiveMQExtensionSupplier(new File("build.gradle"));
This should be the root directory, not "build.gradle"

2020-12-16 15:23 UTC, SgtSilvio commented on core/src/main/java/com/hivemq/testcontainer/core/GradleHiveMQExtensionSupplier.java
> +            final @NotNull File gradleProjectDirectory) {
```suggestion
    public GradleHiveMQExtensionSupplier(final @NotNull File gradleProjectDirectory) {
```

2020-12-16 15:31 UTC, SgtSilvio commented on readme.md
> +Since HiveMQ's 4.4 release, HiveMQ Docker images come with the HiveMQ Extension for Kafka, the HiveMQ Bridge Extension
```suggestion
Since HiveMQ's 4.4 release, HiveMQ Docker images come with the HiveMQ Extension for Kafka, the HiveMQ Enterprise Bridge Extension
```

2020-12-16 15:38 UTC, SgtSilvio approved these changes

2020-12-16 15:55 UTC, merged